#!/usr/bin/env bash

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOUNT_TARGET="${SOURCE_DIR}/target"
INTERACTIVE="-i"
NVIM_CACHE_DIR="$HOME/.nvim-container"

if ! [[ -d "${MOUNT_TARGET}" ]]; then
  mkdir "${MOUNT_TARGET}"
fi

if ! [[ -d "${NVIM_CACHE_DIR}" ]]; then
  mkdir -p "${NVIM_CACHE_DIR}"
fi

# Make absolute
MOUNT_TARGET="$(cd ${MOUNT_TARGET} && pwd)"

# Set docker shell interactive if stdin is open
if [[ -t 0 ]] && [[ "x${INTERACTIVE}" != "x" ]]; then
  INTERACTIVE="${INTERACTIVE} --tty"
fi

FZF_DEFAULT_OPTS="
--border \
--layout=reverse \
--info=inline \
--height=50% \
--color 16 \
--preview-window=:hidden \
--preview '([[ -f {} ]] \
	&& (bat --style=numbers --color=always {} \
	|| cat {})) \
	|| ([[ -d {} ]] && (tree -C {} | less)) \
	|| echo {} 2> /dev/null | head -200'
--bind '?:toggle-preview'
"

docker run \
  --rm \
  -e NOTES=$NOTES \
  -e BAT_THEME="Nord" \
  -e FZF_DEFAULT_COMMAND="fd" \
  -e FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS" \
  -v "$PWD":/ide:z \
  -v ~/.nvim-container/coc:/root/.config/coc:z \
  -v ~/.nvim-container/backups:/root/.config/nvim/backups:z \
  -v ${MOUNT_TARGET}:/target:delegated \
  --workdir /ide \
  ${INTERACTIVE} \
  casonadams/vi \
  vi "/ide/${1}"
